language: node_js

node_js:
  - lts/*

cache: yarn

notifications:
  email: false

install: yarn --ignore-engines

jobs:
  include:
    - stage: Lint 
      script: yarn lint

    - stage: Test
      script: yarn test

    - stage: Coverage
      script:
        jest --coverage && cat ./coverage/lcov.info |
        ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

deploy:
  provider: script
  skip_cleanup: true
  script: yarn semantic-release
