language: node_js

node_js:
  - lts/*

cache: yarn

notifications:
  email: false

install: yarn --ignore-engines

jobs:
  include:
    - stage: Lint 
      script: yarn lint

    - stage: Test
      script: yarn test

deploy:
  provider: script
  skip_cleanup: true
  script: yarn semantic-release
